### PR TITLE
Some suggestions

### PR DESCRIPTION
**Pull request by etoews**
Feel free to use zero to many of these suggestions. If you only want some suggestions, just close this PR or change it pre-merge.

I'm not sure if that last one should be "Jupyter" or "JupyterHub".

### CODE REVIEW

**Comment by carolynvs** [comment]
I _think_ that since I am talking about what is running on the user's cluster (and not howtowhale), that Jupyter is the right term. If I were talking about what is on howtowhale, then it would be JupyterHub.

**Comment by filler** [comment]
Added some skrilla from Cloud DNS wrt ChatOps for the abstract.

**Comment by carolynvs** [comment]
@smashwilson @filler @everett-toews  Awesome! Thanks for the updates, this is looking good. Unless I hear back with more, this is what I'll submit on Monday.

**Pull request merged**
