### PR TITLE
Add the ChatOps to the TalkOps

### PR DESCRIPTION
**Pull request by filler**
This should be the needful for talking bout Cloud DNS, ChatOps, Carina.

This includes a speaker bumper slide for myself.  I think some of the
order needs to change up also?  Based on the title slide and then order
when you march through the deck.

### CODE REVIEW

**Comment by filler** [comment]
lmk what you think @smashwilson @carolynvs.  

The slide count is a bit high, but I can fly through them and keep capped at 10m.

**Comment by smashwilson** [comment]
:+1: Looks fine so far.

> Based on the title slide and then order when you march through the deck.

Oh yeah, I noticed that too.

What order should we use? I've gotten a little used to the slide order (@filler :point_right: @smashwilson :point_right: @carolynvs) but we could switch it up if you'd prefer.

**Comment by carolynvs** [comment]
Yeah let's stick with the slide order, @filler -> @smashwilson -> @carolynvs. Want to fix the title/thank you slides to match?

**Comment by carolynvs** [comment]
Also feel free to merge whenever you are ready.

**Pull request merged**
